### ISSUE TITLE
[Bug] ad_group_history - error with coalesce between JSON and string

### ISSUE THREAD

**Issue by omirobarcelo** [fivetran/dbt_tiktok_ads_source#16]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

When building a project, there's an error with the `stg_tiktok_ads__ad_group_history` because it is trying to coalesce a JSON value and a string value.  
I believe the issue might come because of an update in Fivetran's export of TikTok Ads.

### Relevant error log or model output

```shell
Database Error in model stg_tiktok_ads__ad_group_history (models/stg_tiktok_ads__ad_group_history.sql)
  No matching signature for function COALESCE for argument types: JSON, STRING. Supported signature: COALESCE([ANY, ...]) at [208:9]
  compiled Code at target/run/tiktok_ads_source/models/stg_tiktok_ads__ad_group_history.sql

---------------------------

Line causing the error:
https://github.com/fivetran/dbt_tiktok_ads_source/blob/c65d8f5140c502db173f46e8e72f9e1a84c5ce4b/models/stg_tiktok_ads__ad_group_history.sql#L39C9-L39C49

---------------------------
Compiled code causing the JSON - string error
    cast(null as STRING) as 
    
    age
    
 , 
    
    
    age_groups
    
 as 
    
    age_groups
    
,
```

### Expected behavior

Coalesce shouldn't produce an error.  
Maybe `age` is not needed anymore, avoiding the coalesce, or `age` can be casted to JSON instead of string. 

### dbt Project configurations

```yml
target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  ad_reporting__facebook_ads_enabled: True
  ad_reporting__google_ads_enabled: True
  ad_reporting__tiktok_ads_enabled: True
  ad_reporting__microsoft_ads_enabled: True
  # The following submodules of the ad_reporting package will be disabled
  ad_reporting__amazon_ads_enabled: False
  ad_reporting__apple_search_ads_enabled: False
  ad_reporting__pinterest_ads_enabled: False
  ad_reporting__linkedin_ads_enabled: False
  ad_reporting__twitter_ads_enabled: False
  ad_reporting__snapchat_ads_enabled: False
  ad_reporting__reddit_ads_enabled: False

models:
  ad_reporting:
    +schema: ad_reporting
  google_ads:
    +schema: ad_reporting
  google_ads_source:
    +schema: ad_reporting
  facebook_ads:
    +schema: ad_reporting
  facebook_ads_source:
    +schema: ad_reporting
  tiktok_ads:
    +schema: ad_reporting
  tiktok_ads_source:
    +schema: ad_reporting
```

### Package versions

```yml
packages:
  - package: dbt-labs/dbt_utils
    version: 1.1.1
  - package: dbt-labs/codegen
    version: 0.11.0
  - package: fivetran/ad_reporting
    version: 1.7.0
```
It also happens with `1.6.1`. In production we have `1.6.1` and I tried upgrading to `1.7.0` to see if it fixes it, but it still shows the same error (just changes the error line from [208:9] to [218:9]).

### What database are you using dbt with?

bigquery

### dbt Version

dbt-bigquery==1.6.5

### Additional Context

The Fivetran warning mentioning the migration to use JSON.

![image](https://github.com/fivetran/dbt_tiktok_ads_source/assets/43706247/16f4c045-20de-452f-8fb6-6c5da099dda1)

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [X] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.
